/** \file      INS_ErrorCode.h
 *  \copyright HangZhou Hikvision System Technology Co.,Ltd. All Right Reserved.
 *  \brief     开放SDK消息回调接口中消息类型以及错误码的定义
 *
 *  \author    pikongxuan
 *  \date      2015/07/07
 */
 
 #ifndef _INS_ERRORCODE_H_
 #define _INS_ERRORCODE_H_

/** \define  MessageInfo 
 *  \brief 消息内容定义，预览和回放时，消息回调接口中消息内容
 */
#define INS_EXECUTION_PROCESS_ADDTASK      "7_1" ///< 任务被成功添加至队列"
#define INS_EXECUTION_PROCESS_TASKDO       "7_2" ///< 任务开始被执行"
#define INS_EXECUTION_PROCESS_PARSE_PARAM  "7_3" ///< 解析参数信息"
#define INS_EXECUTION_PROCESS_LOCAL        "7_4" ///< :判断局域网"
#define INS_EXECUTION_PROCESS_CHECKPWD	   "7_5" ///< :验证设备密码"
#define INS_EXECUTION_PROCESS_NETTYPE      "7_5" ///< :选择取流方式"
#define INS_EXECUTION_PROCESS_PSIA         "7_6_1"///<:尝试使用PSIA方式取流"
#define INS_EXECUTION_PROCESS_P2P          "7_6_2"///<:尝试使用P2P方式取流"
#define INS_EXECUTION_PROCESS_VTDU         "7_6_3"///<:尝试使用VTDU方式取流"
#define INS_EXECUTION_PROCESS_TASKEND      "7_7_1"///<:尝试取流失败，结束取流"
#define INS_EXECUTION_PROCESS_TASKEND_SUCC "7_7_2"///<:尝试取流成功，任务结束，等待数据流上来"
#define INS_EXECUTION_PROCESS_NEXT         "7_8"  ///<:尝试取流失败，切换取流方式"
#define INS_EXECUTION_PROCESS_PSIA_PORT    "7_9"  ///<:获取公网PSIA取流端口" 


/// 消息回调中错误码定义， 对于消息回调接口中的错误码
#define INS_ERROR_NOERROR                     0 ///<无错误
#define INS_ERROR_LOAD_RTSP_FAILED            1 ///<加载rtsp库失败
#define INS_ERROR_LOAD_PLAYCTRL_FAILED        2 ///<加载播放库失败
#define INS_ERROR_LOAD_SYSTRANSFORM_FAILED    3 ///<加载转封装库失败
#define INS_ERROR_LOAD_HTTPCLIENT_FAILED      4 ///<加载http库失败
#define INS_ERROR_PARAMETER_ERROR             5 ///<参数错误
#define INS_ERROR_ORDER_ERROR                 6 ///<调用顺序错误
#define INS_ERROR_ALLOC_RESOURCE_FAILED       7 ///<分配资源失败
#define INS_ERROR_NOT_INITLIB                 8 ///<没有初始化
#define INS_ERROR_OPERTION_NOSUPPORT          9 ///<操作不支持
#define INS_ERROR_OPENFILE_ERROR              10 ///<打开文件失败
#define INS_ERROR_WRITEFILE_ERROR             11 ///<写文件失败
#define INS_ERROR_READFILE_ERROR              12 ///<读文件失败
#define INS_ERROR_INIT_HPR_FAILED             13 ///<初始化hpr库失败
#define INS_ERROR_AUDIO_MONOPOLIZED           14 ///<声卡被独占
#define INS_ERROR_CREATE_SOCKET_ERROR         15 ///<创建socket失败
#define INS_ERROR_NETWORK_CONNECT_FAILED      16 ///<连接失败
#define INS_ERROR_NETWORK_SEND_ERROR          17 ///<发送失败
#define INS_ERROR_NETWORK_RECV_ERROR          18 ///<接收失败
#define INS_ERROR_NETWORK_SEND_TIMEOUT        19 ///<发送超时
#define INS_ERROR_NETWORK_RECV_TIMEOUT        20 ///<接收超时
#define INS_ERROR_NETWORK_RESOLVE_FAILED      21 ///<域名解析错误
#define INS_ERROR_XML_PARSE_ERROR             22 ///<xml解析错误
#define INS_ERROR_XML_NODE_ERROR              23 ///<xml结点错误
#define INS_ERROR_NO_EXCEL_DRIVER_ERROR       24 ///<没有安装Excel驱动
#define INS_ERROR_PARSE_URL_FAILED            25 ///<URL解析失败
#define INS_ERROR_LOADRTSPSDKPROC_ERROR       26 ///<找不到rtsp接口地址
#define INS_ERROR_LOADPLAYERSDKPROC_ERROR     27 ///<找不到播放库接口地址
#define INS_ERROR_LOADSYSTRANSFORMPROC_ERROR  28 ///<找不到转封装库接口地址
#define INS_ERROR_LOADHTTPSDKPROC_ERROR       29 ///<找不到http库接口地址
#define INS_ERROR_START_WAVEIN_FAILED         30 ///<开始音频采集失败
#define INS_ERROR_START_WAVEOUT_FAILED        31 ///<开始音频播放失败
#define INS_ERROR_INIT_G722_CODEC_FAILED      32 ///<初始化G722编解码失败
#define INS_ERROR_NOT_ENOUGH_DISK_FREESPACE   33 ///<磁盘空间不足
#define INS_ERROR_FILE_ALREADY_EXIST          34 ///<文件已存在

#define INS_ERROR_LOAD_PPV_FAILED             35  ///<加载ppv库失败
#define INS_ERROR_LOADPPVSDKPROC_ERROR        36 ///<找不到libPPVClient接口地址

#define INS_ERROR_LOAD_STUN_FAILED             37  ///<加载stun库失败
#define INS_ERROR_LOADSTUNSDKPROC_ERROR        38  ///<找不到StunClientLib接口地址

#define INS_ERROR_RECORD_FILE_NOT_EXIST        39 ///< 找不到指定时间范围内的录像文件
#define INS_ERROR_FAILED_RTSP_PORT             40 ///< 通过PSIA取流，获取RTSP端口失败

#define INS_ERROR_SSL_CONNECT_FAILED           41 ///<SSL方式连接失败
#define INS_ERROR_JSON_PARSE_ERROR             42 ///<JSON解析失败

#define INS_ERROR_LOADCASSDKPROC_ERROR         43 ///<找不到libCASClient接口地址
#define INS_ERROR_LOAD_CAS_FAILED              44  ///<加载CASClient库失败
#define INS_ERROR_OPERATIONCODE_FAILED         45  ///<获取操作码失败
#define INS_ERROR_LOAD_GETHDSIGN_FAILED        46  ///<加载libGetHDSign库失败

#define INS_ERROR_HDSIGN_FAILED				  47  ///<获取硬件特征码失败
#define INS_ERROR_NULL_ADDRESS				  48  ///<GetIpAddress返回IP为空

/// rtsp库错误码
#define INS_ERROR_RTSP_INIT_FAILED           50
#define INS_ERROR_RTSP_NOT_INIT              51
#define INS_ERROR_RTSP_PARSE_ERROR           52
#define INS_ERROR_RTSP_STATUS_ERROR          53
#define INS_ERROR_RTSP_INIT_RTP_ERROR        54
#define INS_ERROR_RTSP_CREATE_SOCKET_ERROR   55
#define INS_ERROR_RTSP_CONNECT_FAILED        56
#define INS_ERROR_RTSP_HTTP_GET_ERROR        57
#define INS_ERROR_RTSP_HTTP_POST_ERROR       58
#define INS_ERROR_RTSP_GETPORT_FAILED        59

/// 海康播放库错误
#define  INS_ERROR_PLAYM4_NOERROR				100	///<no error
#define	 INS_ERROR_PLAYM4_PARA_OVER				101	///<input parameter is invalid;
#define  INS_ERROR_PLAYM4_ORDER_ERROR			102	///<The order of the function to be called is error.
#define	 INS_ERROR_PLAYM4_TIMER_ERROR			103	///<Create multimedia clock failed;
#define  INS_ERROR_PLAYM4_DEC_VIDEO_ERROR		104	///<Decode video data failed.
#define  INS_ERROR_PLAYM4_DEC_AUDIO_ERROR		105	///<Decode audio data failed.
#define	 INS_ERROR_PLAYM4_ALLOC_MEMORY_ERROR		106	///<Allocate memory failed.
#define  INS_ERROR_PLAYM4_OPEN_FILE_ERROR		107	///<Open the file failed.
#define  INS_ERROR_PLAYM4_CREATE_OBJ_ERROR		108	///<Create thread or event failed
#define  INS_ERROR_PLAYM4_CREATE_DDRAW_ERROR		109	///<Create DirectDraw object failed.
#define  INS_ERROR_PLAYM4_CREATE_OFFSCREEN_ERROR 110	///<failed when creating off-screen surface.
#define  INS_ERROR_PLAYM4_BUF_OVER			    111	///<buffer is overflow
#define  INS_ERROR_PLAYM4_CREATE_SOUND_ERROR	    112	///<failed when creating audio device.	
#define	 INS_ERROR_PLAYM4_SET_VOLUME_ERROR	    113	///<Set volume failed
#define  INS_ERROR_PLAYM4_SUPPORT_FILE_ONLY	    114	///<The function only support play file.
#define  INS_ERROR_PLAYM4_SUPPORT_STREAM_ONLY	115	///<The function only support play stream.
#define  INS_ERROR_PLAYM4_SYS_NOT_SUPPORT		116	///<System not support.
#define  INS_ERROR_PLAYM4_FILEHEADER_UNKNOWN     117	///<No file header.
#define  INS_ERROR_PLAYM4_VERSION_INCORRECT	    118	///<The version of decoder and encoder is not adapted.  
#define  INS_ERROR_PLAYM4_INIT_DECODER_ERROR     119	///<Initialize decoder failed.
#define  INS_ERROR_PLAYM4_CHECK_FILE_ERROR	    120	///<The file data is unknown.
#define  INS_ERROR_PLAYM4_INIT_TIMER_ERROR	    121	///<Initialize multimedia clock failed.
#define	 INS_ERROR_PLAYM4_BLT_ERROR			    122	///<Blt failed.
#define  INS_ERROR_PLAYM4_UPDATE_ERROR		    123	///<Update failed.
#define  INS_ERROR_PLAYM4_OPEN_FILE_ERROR_MULTI  124   ///<openfile error, streamtype is multi
#define  INS_ERROR_PLAYM4_OPEN_FILE_ERROR_VIDEO  125   ///<openfile error, streamtype is video
#define  INS_ERROR_PLAYM4_JPEG_COMPRESS_ERROR    126   ///<JPEG compress error
#define  INS_ERROR_PLAYM4_EXTRACT_NOT_SUPPORT    127	///<Don't support the version of this file.
#define  INS_ERROR_PLAYM4_EXTRACT_DATA_ERROR     128	///<extract video data failed.
#define  INS_ERROR_PLAYM4_SECRET_KEY_ERROR       129	///<Secret key is error ///<add 20071218
#define  INS_ERROR_PLAYM4_DECODE_KEYFRAME_ERROR  130 ///< 解码关键帧失败
#define  INS_ERROR_PLAYM4_NEED_MORE_DATA         131 ///< 数据不足
#define  INS_ERROR_PLAYM4_INVALID_PORT           132 ///< 无效端口号
#define  INS_ERROR_PLAYM4_NOT_FIND               133 ///< 查找失败
#define  INS_ERROR_PLAYM4_FAIL_UNKNOWN           199 ///< 未知的错误

/// common   error  2000~3000
#define INS_ERROR_V17_COMMON_BASE					2000
#define INS_ERROR_V17_GET_OPERATIONCODE_ERROR		INS_ERROR_V17_COMMON_BASE+1 ///<获取操作码失败
#define INS_ERROR_V17_GET_TOKEN_ERROR				INS_ERROR_V17_COMMON_BASE+2 ///<获取取流token失败
#define INS_ERROR_V17_SETAUDIOINCALLBACK_ERROR		INS_ERROR_V17_COMMON_BASE+3 ///<设置语音采集回调播放失败
#define INS_ERROR_V17_STARTPLAY_ERROR				INS_ERROR_V17_COMMON_BASE+4 ///<开启语音播放失败
#define INS_ERROR_V17_STARTAUDIOIN_ERROR				INS_ERROR_V17_COMMON_BASE+5 ///<语音采集开启播放失败
#define INS_ERROR_V17_TTS_CREATETALK_ERROR			INS_ERROR_V17_COMMON_BASE+6 ///<tts TALK_VTDU CreateTalk error
#define INS_ERROR_V17_TTS_SETDATACALLBACK_ERROR		INS_ERROR_V17_COMMON_BASE+7 ///<tts TALK_VTDU SetDataCallBack error
#define INS_ERROR_V17_TTS_SETMSGCALLBACK_ERROR		INS_ERROR_V17_COMMON_BASE+8 ///<tts TALK_VTDU SetMsgCallBack error
#define INS_ERROR_V17_TTS_STARTTALK_ERROR		    INS_ERROR_V17_COMMON_BASE+9 ///<tts TALK_VTDU StartTalk error
#define INS_ERROR_V17_CAS_CREATESESSION_ERROR		INS_ERROR_V17_COMMON_BASE+10 ///<cas TALK_TCP/TALK_UDP CreateSession error
#define INS_ERROR_V17_CAS_VOICETALKSTART_ERROR		INS_ERROR_V17_COMMON_BASE+11 ///<cas TALK_TCP/TALK_UDP VoiceTalkStart error
#define INS_ERROR_V17_PERMANENTKEY_EXCEPTION         INS_ERROR_V17_COMMON_BASE+12   ///<重新输入密钥  1.明文密钥和输入MD5密钥不相等 
#define INS_ERROR_V17_VTDU_OPERKEY_ERROR				INS_ERROR_V17_COMMON_BASE+13 ///<VTDU返回的操作码错误或信令密钥错误
#define INS_ERROR_V17_STOPAUDIOIN_ERROR				INS_ERROR_V17_COMMON_BASE+14 ///<停止语音采集失败
#define INS_ERROR_V17_STOPPLAY_ERROR					INS_ERROR_V17_COMMON_BASE+15 ///<停止语音播放失败
#define INS_ERROR_V17_STOPAUDIOIN_SUCC				INS_ERROR_V17_COMMON_BASE+16 ///<停止语音采集成功
#define INS_ERROR_V17_STOPPLAY_SUCC					INS_ERROR_V17_COMMON_BASE+17 ///<停止语音播放成功
#define INS_ERROR_V17_VTDU_TIMEOUT					INS_ERROR_V17_COMMON_BASE+21	///<流媒体向设备发送或接受信令超时
#define INS_ERROR_V17_VTDU_CKECK_TOKEN				INS_ERROR_V17_COMMON_BASE+22 ///<验证token失败
#define INS_ERROR_V17_CLIENT_URL_ERROR			    INS_ERROR_V17_COMMON_BASE+23 ///<客户端的URL格式错误
#define INS_ERROR_V17_VTDU_CLIENT_TIMEOUT			INS_ERROR_V17_COMMON_BASE+25 ///<vtdu客户端接收回应超时
#define INS_ERROR_V17_STREAM_SESSION_ERROR			INS_ERROR_V17_COMMON_BASE+26 ///<取流session出错	
#define INS_ERROR_V17_WAIT_HEADER_TIMEOUT			INS_ERROR_V17_COMMON_BASE+27 ///<等待流头超时
#define INS_ERROR_V17_USER_STOP						INS_ERROR_V17_COMMON_BASE+28 ///<用户停止
#define INS_ERROR_V17_DECRYPT_ERROR					INS_ERROR_V17_COMMON_BASE+29  ///<解密失败

/// vtud相关
#define INS_ERROR_V17_VTDU_CREATE_SESSION			INS_ERROR_V17_COMMON_BASE+31		 ///<vtdu取流创建session失败
#define INS_ERROR_V17_VTDU_DESTORY_SESSION			INS_ERROR_V17_COMMON_BASE+32		 ///<vtdu取流销毁session失败
#define INS_ERROR_V17_VTDU_START						INS_ERROR_V17_COMMON_BASE+33		 ///<vtdu取流开始失败，返回-1时设置
#define INS_ERROR_V17_VTDU_STOP						INS_ERROR_V17_COMMON_BASE+34		///<vtdu取流停止失败
#define INS_ERROR_V17_VTDU_PAUSE						INS_ERROR_V17_COMMON_BASE+35		 ///<vtdu取流暂停失败
#define INS_ERROR_V17_VTDU_RESUME					INS_ERROR_V17_COMMON_BASE+36		///<vtdu取流恢复失败
#define INS_ERROR_V17_VTDU_CHANGE_RATE				INS_ERROR_V17_COMMON_BASE+37		///<vtdu取流改变速率失败


#define INS_ERROR_V17_VTDU_TOKEN_NO_AUTHORITY	INS_ERROR_V17_COMMON_BASE+44	 ///<VTDU token无权限
#define INS_ERROR_V17_VTDU_SESSION_NO_EXIST		INS_ERROR_V17_COMMON_BASE+45	 ///<VTDU session不存在
#define INS_ERROR_V17_VTDU_TOKEN_OTHER			INS_ERROR_V17_COMMON_BASE+46	 ///<VTDU 验证token的他异常（不具体）
#define INS_ERROR_V17_VTDU_TOKEN_NOCONNECT_VTM	INS_ERROR_V17_COMMON_BASE+47	 ///<VTDU 客户端连接不上VTM
#define INS_ERROR_V17_VTDU_TOKEN_NOCONNECT_VTDU	INS_ERROR_V17_COMMON_BASE+48	 ///<VTDU 客户端连接不上VTDU
#define INS_ERROR_V17_INVALID_DEVICE_CHANNAL			INS_ERROR_V17_COMMON_BASE+49 ///<设备通道错
#define INS_ERROR_V17_DEVICE_UNSUPPORT_STREAMTYPE	INS_ERROR_V17_COMMON_BASE+50 ///<设备不支持的码流类型
#define INS_ERROR_V17_DEVICE_UNCONNECT_VTDU			INS_ERROR_V17_COMMON_BASE+51 ///<设备连接不上流媒体
#define INS_ERROR_V17_CLIENT_ERROR_CASIP				INS_ERROR_V17_COMMON_BASE+52 ///<客户端给的cas地址信息错误
#define INS_ERROR_V17_VIDEO_SHARED_TIMEEND			INS_ERROR_V17_COMMON_BASE+53 ///<视频分享时间已经结束
#define INS_ERROR_V17_VTDU_RECV_HEADER_TIMEOUT		INS_ERROR_V17_COMMON_BASE+54	///<流媒体接收流头超时8s
#define INS_ERROR_V17_VTDU_VTDU_IPARAMTYPE_ERROR					INS_ERROR_V17_COMMON_BASE+55		///< Vtdu iParamType error
#define INS_ERROR_V17_GET_OPERATIONCODE_PARAMETER_ERROR			INS_ERROR_V17_COMMON_BASE+56		///< 获取操作码参数错误
#define INS_ERROR_V17_REGET_OPERATIONCODE_DEV_NOT_FOUND			INS_ERROR_V17_COMMON_BASE+57		///< 无法找到设备
#define INS_ERROR_V17_GETTOKEN_URL_OR_CLIENTSESSION_NULL			INS_ERROR_V17_COMMON_BASE+58		///< 获取Token参数错误
#define INS_ERROR_V17_GETTOKEN_EMPTY_TOKEN						INS_ERROR_V17_COMMON_BASE+59		///< 获取的Token为空
#define INS_ERROR_V17_FIND_FILE_FAILED 							INS_ERROR_V17_COMMON_BASE+60		///< 找不到可用文件

/************************************************************************/
/*note: vtdu client libary error code base on NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE
/*tranform rule: the code given by the libary add NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE (eg.2200+code)
/*so we reserve 2200-2600 for these code
/************************************************************************/
#define NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE		2200
#define NS_ERROR_PRIVATE_VTDU_BAD_MSG		        NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 4                	//信令消息解析非法
#define NS_ERROR_PRIVATE_VTDU_NO_ENOUGH_ROOM		NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 5         			//内存资源不足
#define NS_ERROR_PRIVATE_VTDU_INVALID_VTDU_HOST		NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 8      			//解析vtm返回vtdu地址不合法
#define NS_ERROR_PRIVATE_VTDU_INVALID_SSN_STREAMKEY	NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 10  				//解析vtm返回会话标识长度不合法
#define NS_ERROR_PRIVATE_VTDU_ALLOCATE_SOCKET_FAIL  NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 22   				//获取系统socket资源失败
#define NS_ERROR_PRIVATE_VTDU_CONNECT_SRV_FAIL      NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 24       			//链接服务器失败
#define NS_ERROR_PRIVATE_VTDU_REQUEST_TIMEOUT       NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 25        			//客户端请求未收到服务端应答
#define NS_ERROR_PRIVATE_VTDU_DISCONNECTED_LINK     NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 26      			//链路断开

#define NS_ERROR_PRIVATE_VTDU_STATUS_402		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 402   				//回放在不到录像文件
#define NS_ERROR_PRIVATE_VTDU_STATUS_403		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 403   				//操作码或信令密钥与设备不匹配
#define NS_ERROR_PRIVATE_VTDU_STATUS_404		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 404   				//设备不在线
#define NS_ERROR_PRIVATE_VTDU_STATUS_405		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 405   				//流媒体向设备发送或接受信令超时/cas响应超时
#define NS_ERROR_PRIVATE_VTDU_STATUS_406		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 406   				//token失效
#define NS_ERROR_PRIVATE_VTDU_STATUS_407		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 407   				//客户端的URL格式错误
#define NS_ERROR_PRIVATE_VTDU_STATUS_409		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 409   				//预览开启隐私保护
#define NS_ERROR_PRIVATE_VTDU_STATUS_410	    	NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 410   				//设备达到最大连接数
#define NS_ERROR_PRIVATE_VTDU_STATUS_411		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 411   				//token无权限
#define NS_ERROR_PRIVATE_VTDU_STATUS_412		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 412   				//session不存在
#define NS_ERROR_PRIVATE_VTDU_STATUS_413		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 413   				//验证token的其他异常（不具体）
#define NS_ERROR_PRIVATE_VTDU_STATUS_415		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 415   				//设备通道错
#define NS_ERROR_PRIVATE_VTDU_STATUS_451		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 451   				//设备不支持的码流类型
#define NS_ERROR_PRIVATE_VTDU_STATUS_452		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 452   				//设备连接预览流媒体服务器失败
#define NS_ERROR_PRIVATE_VTDU_STATUS_454		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 454   				//视频分享时间已经结束
#define NS_ERROR_PRIVATE_VTDU_STATUS_491		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 491   				//相同请求正在处理，拒绝本次处理
#define NS_ERROR_PRIVATE_VTDU_STATUS_500		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 500   				//流媒体服务器内部处理错误
#define NS_ERROR_PRIVATE_VTDU_STATUS_503		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 503   				//vtm分配vtdu服务器失败
#define NS_ERROR_PRIVATE_VTDU_STATUS_544		    NS_ERROR_PRIVATE_VTDU_CLN_ERR_CODE + 544   				//设备返回无视频源

/// CASLIb  error  3000~4000
#define  INS_ERROR_CASLIB_BASE					3000
#define  INS_ERROR_CASLIB_MSG_UNKNOW_ERROR	INS_ERROR_CASLIB_BASE+1	///<未知错误	
#define  INS_ERROR_CASLIB_MSG_PARAMS_ERROR	INS_ERROR_CASLIB_BASE+2	///<报文参数错误	
#define  INS_ERROR_CASLIB_MSG_PARSE_FAILED	INS_ERROR_CASLIB_BASE+3	///<报文解析错误	

#define  INS_ERROR_CASLIB_MSG_COMMAND_UNKNOW				INS_ERROR_CASLIB_BASE+6	///<非法命令	
#define  INS_ERROR_CASLIB_MSG_COMMAND_NO_LONGER_SUPPORTED	INS_ERROR_CASLIB_BASE+7	///<过时命令	
#define  INS_ERROR_CASLIB_MSG_COMMAND_NOT_SUITABLE			INS_ERROR_CASLIB_BASE+8	///<错误命令	

#define  INS_ERROR_CASLIB_MSG_CHECKSUM_ERROR	INS_ERROR_CASLIB_BASE+11	///<校验码错误	

#define  INS_ERROR_CASLIB_MSG_VERSION_UNKNOW				INS_ERROR_CASLIB_BASE+16	///<协议版本错误	
#define  INS_ERROR_CASLIB_MSG_VERSION_NO_LONGER_SUPPORTED	INS_ERROR_CASLIB_BASE+17	///<协议版本过低	
#define  INS_ERROR_CASLIB_MSG_VERSION_FORBIDDEN				INS_ERROR_CASLIB_BASE+18	///<协议版本被禁止	

#define  INS_ERROR_CASLIB_MSG_SERIAL_NOT_FOR_CIVIL			INS_ERROR_CASLIB_BASE+21	///<序列号解析失败	
#define  INS_ERROR_CASLIB_MSG_SERIAL_FORBIDDEN				INS_ERROR_CASLIB_BASE+22	///<序列号被禁止	
#define  INS_ERROR_CASLIB_MSG_SERIAL_DUPLICATE				INS_ERROR_CASLIB_BASE+23	///<序列号重复	
#define  INS_ERROR_CASLIB_MSG_SERIAL_FLUSHED_IN_A_SECOND		INS_ERROR_CASLIB_BASE+24	///<相同序列号短时间内大量重复请求	
#define  INS_ERROR_CASLIB_MSG_SERIAL_NO_LONGER_SUPPORTED		INS_ERROR_CASLIB_BASE+25	///<序列号不再支持	

#define  INS_ERROR_CASLIB_MSG_LOCAL_SERVER_BUSY		INS_ERROR_CASLIB_BASE+31	///<本地无法响应	
#define  INS_ERROR_CASLIB_MSG_LOCAL_SERVER_REFUSED	INS_ERROR_CASLIB_BASE+32	///<本地主动拒绝	
#define  INS_ERROR_CASLIB_REG_CANNOT_AFFORD_PU			INS_ERROR_CASLIB_BASE+33	///<无法接受请求	
#define  INS_ERROR_CASLIB_REG_CRYPTO_UNMATCHED			INS_ERROR_CASLIB_BASE+34	///<设备加密算法不匹配	

#define  INS_ERROR_CASLIB_MSG_DEV_TYPE_INVAILED				INS_ERROR_CASLIB_BASE+36	///<设备类型错误	
#define  INS_ERROR_CASLIB_MSG_DEV_TYPE_NO_LONGGER_SUPPORTED	INS_ERROR_CASLIB_BASE+37	///<设备类型不再支持	

#define  INS_ERROR_CASLIB_MSG_PU_BUSY				INS_ERROR_CASLIB_BASE+41	///<设备无法响应	
#define  INS_ERROR_CASLIB_MSG_OPERATION_FAILED		INS_ERROR_CASLIB_BASE+42	///<操作码错误	
#define  INS_ERROR_CASLIB_PU_NO_CRYPTO_FOUND				INS_ERROR_CASLIB_BASE+43	///<设备或平台未找到对应的加密算法	
#define  INS_ERROR_CASLIB_MSG_PU_REFUSED				INS_ERROR_CASLIB_BASE+44	///<拒绝	
#define  INS_ERROR_CASLIB_MSG_PU_NO_RESOURCE			INS_ERROR_CASLIB_BASE+45	///<没有可用资源	 设备连接上线
#define  INS_ERROR_CASLIB_MSG_PU_CHANNEL_ERROR		INS_ERROR_CASLIB_BASE+46	///<通道错	
#define  INS_ERROR_CASLIB_SYSTEM_COMMAND_PU_COMMAND_UNSUPPORTED		INS_ERROR_CASLIB_BASE+47	///<不支持的命令	
#define  INS_ERROR_CASLIB_SYSTEM_COMMAND_PU_NO_RIGHTS_TO_DO_COMMAND	INS_ERROR_CASLIB_BASE+48	///<没有权限	
#define  INS_ERROR_CASLIB_MSG_NO_SESSION_FOUND		INS_ERROR_CASLIB_BASE+49	///<没有找到会话

#define  INS_ERROR_CASLIB_PREVIEW_CHANNEL_BUSY			INS_ERROR_CASLIB_BASE+51	///<该通道已在发流	
#define  INS_ERROR_CASLIB_PREVIEW_CLIENT_BUSY			INS_ERROR_CASLIB_BASE+52 ///<取流地址重复	
#define  INS_ERROR_CASLIB_PREVIEW_STREAM_UNSUPPORTED		INS_ERROR_CASLIB_BASE+53	///<不支持的码流类型	
#define  INS_ERROR_CASLIB_PREVIEW_TRANSPORT_UNSUPPORTED	INS_ERROR_CASLIB_BASE+54	///<不支持的传输方式	
#define  INS_ERROR_CASLIB_PREVIEW_CONNECT_SERVER_FAIL	INS_ERROR_CASLIB_BASE+55	///<连接预览流媒体服务器失败 +
#define  INS_ERROR_CASLIB_PREVIEW_QUERY_WLAN_INFO_FAIL	INS_ERROR_CASLIB_BASE+56	///<查询设备公网出口地址失败

#define  INS_ERROR_CASLIB_RECORD_SEARCH_START_TIME_ERROR	INS_ERROR_CASLIB_BASE+61	///<查找录像开始时间错	
#define  INS_ERROR_CASLIB_RECORD_SEARCH_STOP_TIME_ERROR	INS_ERROR_CASLIB_BASE+62	///<查找录像结束时间错	
#define  INS_ERROR_CASLIB_RECORD_SEARCH_FAIL				INS_ERROR_CASLIB_BASE+63	///<查找录像失败	+

#define  INS_ERROR_CASLIB_PLAYBACK_TYPE_UNSUPPORTED		INS_ERROR_CASLIB_BASE+66	///<不支持的回放类型	
#define  INS_ERROR_CASLIB_PLAYBACK_NO_FILE_MATCHED		INS_ERROR_CASLIB_BASE+67	///<没有找到文件	
#define  INS_ERROR_CASLIB_PLAYBACK_START_TIME_ERROR		INS_ERROR_CASLIB_BASE+68	///<开始时间错误	
#define  INS_ERROR_CASLIB_PLAYBACK_STOP_TIME_ERROR		INS_ERROR_CASLIB_BASE+69	///<错误的结束时间	
#define  INS_ERROR_CASLIB_PLAYBACK_NO_FILE_FOUND			INS_ERROR_CASLIB_BASE+70	///<该时间段内没有录像	
#define  INS_ERROR_CASLIB_PLAYBACK_CONNECT_SERVER_FAIL	INS_ERROR_CASLIB_BASE+71	///<连接回放服务器端失败

#define  INS_ERROR_CASLIB_TALK_ENCODE_TYPE_UNSUPPORTED	INS_ERROR_CASLIB_BASE+76	///<不支持的语音编码类型	
#define  INS_ERROR_CASLIB_TALK_CHANNEL_BUSY				INS_ERROR_CASLIB_BASE+77	///<该通道已在对讲	
#define  INS_ERROR_CASLIB_TALK_CLIENT_BUSY				INS_ERROR_CASLIB_BASE+78	///<和目的地址已有链接	
#define  INS_ERROR_CASLIB_TALK_UNSUPPORTED				INS_ERROR_CASLIB_BASE+79	///<not support talk
#define  INS_ERROR_CASLIB_TALK_CHANNO_ERROR				INS_ERROR_CASLIB_BASE+80	///<通道号错误
#define  INS_ERROR_CASLIB_TALK_CONNECT_SERVER_FAILED		INS_ERROR_CASLIB_BASE+81	///<连接语音服务器失败
#define  INS_ERROR_CASLIB_TALK_CONNECT_REFUSED			INS_ERROR_CASLIB_BASE+82	///<设备拒绝
#define  INS_ERROR_CASLIB_TALK_CONNECT_CAPACITY_LIMITED	INS_ERROR_CASLIB_BASE+83	///<设备资源受限

#define  INS_ERROR_CASLIB_FORMAT_NO_LOCAL_STORAGE	INS_ERROR_CASLIB_BASE+86	///<没有本地存储	
#define  INS_ERROR_CASLIB_FORMAT_FORMATING			INS_ERROR_CASLIB_BASE+87	///<正在格式化中	
#define  INS_ERROR_CASLIB_FORMAT_FAILED				INS_ERROR_CASLIB_BASE+88	///<尝试格式化失败	

#define  INS_ERROR_CASLIB_UPGRADE_PU_REQUEST_REFUSED				INS_ERROR_CASLIB_BASE+91	///<服务器拒绝设备升级请求	
#define  INS_ERROR_CASLIB_UPGRADE_PU_REQUEST_VERSION_NOT_FOUND	INS_ERROR_CASLIB_BASE+92	///<没有找到请求版本	
#define  INS_ERROR_CASLIB_UPGRADE_PU_REQUEST_UNNEEDED			INS_ERROR_CASLIB_BASE+93	///<不需要升级	
#define  INS_ERROR_CASLIB_UPGRADE_PU_REQUEST_NO_SERVER_ONLINE	INS_ERROR_CASLIB_BASE+94	///<没有升级服务器在线	
#define  INS_ERROR_CASLIB_UPGRADE_PU_REQUEST_ALL_SERVER_BUSY		INS_ERROR_CASLIB_BASE+95	///<所有升级服务器都达到最大负载	

#define  INS_ERROR_CASLIB_UPGRADE_PU_UPGRADING					INS_ERROR_CASLIB_BASE+101 ///<正在软件升级	
#define  INS_ERROR_CASLIB_UPGRADE_PU_UPGRAD_FAILED				INS_ERROR_CASLIB_BASE+102 ///<升级失败（包含未知错误）
#define  INS_ERROR_CASLIB_UPGRADE_PU_UPGRAD_WRITE_FLASH_FAILED	INS_ERROR_CASLIB_BASE+103 ///<升级写Flash失败
#define  INS_ERROR_CASLIB_UPGRADE_PU_UPGRAD_LANGUAGE_DISMATCH	INS_ERROR_CASLIB_BASE+104 ///<升级语言不匹配

#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_NO_USER_MATHCED					INS_ERROR_CASLIB_BASE+106	///<密码更新失败，没有对应用户	
#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_ORIGINAL_PASSWORD_ERROR			INS_ERROR_CASLIB_BASE+107	///<密码跟新失败，原始密码错误	
#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_NEW_PASSWORD_DECRYPTE_FAILED    INS_ERROR_CASLIB_BASE+108	///<密码更新失败，新密码解密失败	
#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_NEW_PASSWORD_CHECK_FAILED		INS_ERROR_CASLIB_BASE+109	///<密码更新失败，新密码不符合规则	
#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_WRITE_FLASH_FAILED				INS_ERROR_CASLIB_BASE+110	///<更新密码失败，写flash失败	
#define  INS_ERROR_CASLIB_PU_PASSWORD_UPDATE_OTHER_FALIURE					INS_ERROR_CASLIB_BASE+111	///<更新密码失败，其他原因	

#define  INS_ERROR_CASLIB_PU_PASSWORD_VERIFY_PASSWORD_ FAILED				INS_ERROR_CASLIB_BASE+116	///<验证密码失败	

#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_REQUEST_NO_PU_FOUNDED			INS_ERROR_CASLIB_BASE+121	///<请求的设备不在线	
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_REQUEST_REFUSED_TO_PROTECT_PU	INS_ERROR_CASLIB_BASE+122	///<为了保护设备，拒绝请求	
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_REQUEST_PU_LIMIT_REACHED		INS_ERROR_CASLIB_BASE+123	///<设备达到链接的客户端上限	
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_TEARDOWN_PU_CONNECTION			INS_ERROR_CASLIB_BASE+124	///<要求客户端断开与设备连接	
#define  INS_ERROR_CASLIB_PU_REFUSE_CLIENT_CONNECTION					INS_ERROR_CASLIB_BASE+125	///<设备拒绝平台发送的客户端连接请求	
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_VERIFY_AUTH_ERROR				INS_ERROR_CASLIB_BASE+126  ///<CAS向验证中心验证用户权限失败
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_REQUEST_PU_OPEN_PRIVACY		INS_ERROR_CASLIB_BASE+127 ///<设备开启隐私保护
#define  INS_ERROR_CASLIB_PLATFORM_CLIENT_NO_SIGN_RELEATED				INS_ERROR_CASLIB_BASE+128		///</<没有关联特征码

#define  INS_ERROR_CASLIB_DEFENCE_TYPE_UNSUPPORTED				INS_ERROR_CASLIB_BASE+131 ///<不支持的布撤防类型
#define	 INS_ERROR_CASLIB_DEFENCE_TYPE_FAILED					INS_ERROR_CASLIB_BASE+132 ///</<布撤防失败
#define  INS_ERROR_CASLIB_DEFENCE_TYPE_FORCE_FAILED				INS_ERROR_CASLIB_BASE+133 ///</<强制布撤防失败
#define  INS_ERROR_CASLIB_DEFENCE_TYPE_NEED_FORCE				INS_ERROR_CASLIB_BASE+134 ///</<需要强制布撤防

#define  INS_ERROR_CASLIB_CLOUD_NOT_FOUND						INS_ERROR_CASLIB_BASE+141 ///<没有找到云存储服务器
#define  INS_ERROR_CASLIB_CLOUD_NO_USER							INS_ERROR_CASLIB_BASE+142 ///<用户未开通云存储
#define  INS_ERROR_CASLIB_CLOUD_FILE_TAIL_REACHED				INS_ERROR_CASLIB_BASE+145 ///<文件已到结尾
#define  INS_ERROR_CASLIB_CLOUD_INVALID_SESSION					INS_ERROR_CASLIB_BASE+146 ///<无效的session
#define  INS_ERROR_CASLIB_CLOUD_INVALID_HANDLE					INS_ERROR_CASLIB_BASE+147 ///<无效的文件
#define  INS_ERROR_CASLIB_CLOUD_UNKNOWN_CLOUD					INS_ERROR_CASLIB_BASE+148 ///<未知的云存储类型
#define  INS_ERROR_CASLIB_CLOUD_UNSUPPORT_FILETYPE				INS_ERROR_CASLIB_BASE+149 ///<不支持的文件类型
#define  INS_ERROR_CASLIB_CLOUD_INVALID_FILE						INS_ERROR_CASLIB_BASE+150 ///<无效的文件
#define  INS_ERROR_CASLIB_CLOUD_QUOTA_IS_FULL					INS_ERROR_CASLIB_BASE+151 ///<配额已满
#define  INS_ERROR_CASLIB_CLOUD_FILE_IS_FULL						INS_ERROR_CASLIB_BASE+152 ///<文件已满

#define INS_ERROR_CASLIB_CLIENT_BASE				INS_ERROR_CASLIB_BASE+200  ///<客户端错误号
#define INS_ERROR_CASLIB_CLIENT_PARAMETER			INS_ERROR_CASLIB_BASE+201  ///<参数错误
#define INS_ERROR_CASLIB_CLIENT_ALLOC_RESOURCE	INS_ERROR_CASLIB_BASE+202  ///<分配资源失败
#define INS_ERROR_CASLIB_CLIENT_SEND_FAILED		INS_ERROR_CASLIB_BASE+203  ///<发送错误
#define INS_ERROR_CASLIB_CLIENT_RECV_FAILED		INS_ERROR_CASLIB_BASE+204  ///<接收错误
#define INS_ERROR_CASLIB_CLIENT_PARSE_XML			INS_ERROR_CASLIB_BASE+205  ///<解析报文错误
#define INS_ERROR_CASLIB_CLIENT_CREATE_XML		INS_ERROR_CASLIB_BASE+205  ///<生成报文错误
#define INS_ERROR_CASLIB_CLIENT_INIT_SOCKET		INS_ERROR_CASLIB_BASE+207  ///<初始化Socket失败
#define INS_ERROR_CASLIB_CLIENT_CREATE_SOCKET		INS_ERROR_CASLIB_BASE+208  ///<创建socket失败
#define INS_ERROR_CASLIB_CLIENT_CONNECT_FAILED	INS_ERROR_CASLIB_BASE+209  ///<连接服务器失败
#define INS_ERROR_CASLIB_CLIENT_NO_INIT			INS_ERROR_CASLIB_BASE+210  ///<CASLIB.dll not init
#define INS_ERROR_CASLIB_CLIENT_OVER_MAX_SESSION	INS_ERROR_CASLIB_BASE+211  ///<超过CASCLIENT库支持的最大数
#define INS_ERROR_CASLIB_CLIENT_SENDTIMEOUT		INS_ERROR_CASLIB_BASE+212  ///<信令发送超时
#define INS_ERROR_CASLIB_CLIENT_RECV_TIMEOUT		INS_ERROR_CASLIB_BASE+213  ///<信令接收超时
#define INS_ERROR_CASLIB_CLIENT_CREATE_PACKET		INS_ERROR_CASLIB_BASE+214  ///<create data packet failed
#define INS_ERROR_CASLIB_CLIENT_PARSE_PACKET		INS_ERROR_CASLIB_BASE+215  ///<解析数据包错误
#define INS_ERROR_CASLIB_CLIENT_FORCE_STOP		INS_ERROR_CASLIB_BASE+216	///<用户中途强行退出
#define INS_ERROR_CASLIB_CLIENT_GETPORT_FAILED	INS_ERROR_CASLIB_BASE+217	///<获取本地端口错误
#define INS_ERROR_CASLIB_CLIENT_BASE64_ENCODE		INS_ERROR_CASLIB_BASE+218	///<base64编码出错
#define INS_ERROR_CASLIB_CLIENT_BASE64_DECODE		INS_ERROR_CASLIB_BASE+219	///<base64 decode failed
#define INS_ERROR_CASLIB_CLIENT_RECV_DATAERROR	INS_ERROR_CASLIB_BASE+220  ///<接收数据错误
#define INS_ERROR_CASLIB_CLIENT_AES_ENCRYPT_FAILED	INS_ERROR_CASLIB_BASE+221  ///<AES加密出错
#define INS_ERROR_CASLIB_CLIENT_AES_DECRYPT_FAILED	INS_ERROR_CASLIB_BASE+222  ///<AES解密出错
#define INS_ERROR_CASLIB_CLIENT_OPERATION_UNSUPPORTED	INS_ERROR_CASLIB_BASE+223  ///<不支持的操作
#define INS_ERROR_CASLIB_CLIENT_ERROR_P2P_FAILED		INS_ERROR_CASLIB_BASE+224 ///<p2p打洞失败
#define INS_ERROR_CASLIB_CLIENT_ERROR_SEND_KEEPLIVE_FAILED		INS_ERROR_CASLIB_BASE+225 ///<发送打洞包失败
#define INS_ERROR_CASLIB_CLIENT_ERROR_INIT_SSL			INS_ERROR_CASLIB_BASE+228  ///<初始化ssl失败
#define INS_ERROR_CASLIB_CLIENT_ERROR_CONNECT_SSL        INS_ERROR_CASLIB_BASE+229  ///<ssl连接失败


#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_OTHER_ERROR				INS_ERROR_CASLIB_BASE+249	///<认证的其他错误			
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_DB_ERROR				INS_ERROR_CASLIB_BASE+250	///<认证的数据库错误
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_PARAMS_ERROR			INS_ERROR_CASLIB_BASE+251	///<认证的参数错误
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_EXEC_ERROR				INS_ERROR_CASLIB_BASE+252	///<认证的执行异常
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_SESSION_ERROR			INS_ERROR_CASLIB_BASE+253	///<认证的session不正常
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_CACHE_ERROR				INS_ERROR_CASLIB_BASE+254	///<认证的缓存异常
#define INS_ERROR_CASLIB_CLIENT_ERROR_VERIFY_AUTH_NONE				INS_ERROR_CASLIB_BASE+255	///<认证的无权限

#endif //_INS_ERRORCODE_H_